# Generated by Django 4.2 on 2024-12-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='name',
            new_name='segment',
        ),
    ]
