# Generated by Django 5.1.3 on 2024-12-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_alter_equipment_options_alter_repair_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plant_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to='plant.employee', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание ремонта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_tasks', to='plant.repair', verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(verbose_name='Начало ремонта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_object_tasks', to='plant.task_object', verbose_name='Объект ремонта'),
        ),
    ]
