# Generated by Django 5.1.3 on 2024-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_plant_post_post_alter_task_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_status',
            field=models.BooleanField(default=False),
        ),
    ]
