# Generated by Django 5.1.3 on 2024-12-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_task_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
